AuthenticationWithCookie/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace AuthenticationWithCookie.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

AuthenticationWithCookie/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using System.Security.Claims;
using System.Text.Encodings.Web;
using System;

namespace AuthenticationWithCookie.Pages;

public class IndexModel : PageModel
{
    [BindProperty]
    public LoginInput LoginInput { get; set; }
    public async Task<IActionResult> OnPost()
   {
        string username = LoginInput.UserName;
        string password = LoginInput.Password;
       if(username==null || password==null) {
          ModelState.AddModelError("", "username and password fields must be entered");
          return Page();
       }
       if(username== "intern" && password== "summer 2023 july")
       {
            var claims = new List<Claim>
            {
            new Claim(ClaimTypes.Name, username),
            new Claim(ClaimTypes.Role, "User"),
            };
            var scheme = CookieAuthenticationDefaults.AuthenticationScheme;
            var claimsIdentity = new ClaimsIdentity(
            claims, CookieAuthenticationDefaults.AuthenticationScheme);
            var authProperties = new AuthenticationProperties
            {
                AllowRefresh = true,
                ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(10),

            };
            var user = new ClaimsPrincipal(claimsIdentity);
            await HttpContext.SignInAsync(scheme, user, authProperties);
            return RedirectToPage("/Index");
        }
       else
       {
            ModelState.AddModelError("", "Invalid username or password");
            return Page();
        }
    }
    public async Task<IActionResult> OnPostLoggingOut()
    {
        await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
        return RedirectToPage("/Index");
    }
}
public class LoginInput
{
    public string UserName { get; set; }
    public string Password { get; set; }
}

AuthenticationWithCookie/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AuthenticationWithCookie.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

AuthenticationWithCookie/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
@if(!User.Identity.IsAuthenticated)
{
   <div class="card" style="padding:7px;">
         <div class="card-body" style="width:200px;">
              <form method="post">
                <div class="username" style="margin:10px;">
                    <label class="myusername">Username</label>
                    <input type="text" name="LoginInput.Username" required title="Please enter your correct username" />
                </div>

                <div class="password" style="margin:10px;">
                    <label class="mypassword">Password</label>
                    <input type="password" name="LoginInput.Password" required title="Please enter your correct password" />
                </div>

                <div class="login" style="margin:10px;">
                    <button type="submit" class="btn btn-primary">Login</button>
                </div>
                <div asp-validation-summary="ModelOnly" class="text-danger no-bullet" style="width:300px; ">
                </div>
                <style>
                    .no-bullet ul, .no-bullet ol {
                        list-style: none;
                    }
                </style>
              </form>
         </div>
   </div>

}
else
{
    <h4>Welcom @User.Identity.Name . you have successfully logged in !</h4>
    <form method="post" asp-page-handler="LoggingOut">
        <button type="submit" class="btn btn-primary">Log out</button>
    </form>

}

AuthenticationWithCookie/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AuthenticationWithCookie</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AuthenticationWithCookie.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">AuthenticationWithCookie</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AuthenticationWithCookie - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>